substitutions:
  _NAME: builder

steps:
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "subiz/$_NAME:$TAG_NAME", "."]

- name: gcr.io/cloud-builders/docker
  entrypoint: sh
  args:
  - -c
  - |
    docker login -u $_DOCKER_USERNAME -p $_DOCKER_PASSWORD
    docker push subiz/$_NAME:$TAG_NAME
